### ISSUE TITLE
cannot edit comment after minimising it

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-app-code-review#42]
In the teacher view, when I minimise a comment, I cannot then edit it, even if I click on the buttons. Looks like the event handlers are removed.

**Comment by spaenleh** [comment]
Good catch, i think the problem is that when the comment is minimized, content is in "collapse" mode. So when the edit button is clicked, the content of the collapsed element switches to the comment Editor, but is not visible because it is still collapsed. And the Minimizing/Maximizing button is not shown here, so there is no way of exiting collapsed mode. Reloading the page works as by default all comments are in "expanded" state but is clearly not ideal. 

Solution :
- Disable "edit", "reply" and "delete" buttons in "collapsed" mode.

What do you think @juancarlosfarah ?

**Comment by spaenleh** [comment]
47770b8 adresses the editing in collapsed state bug.

There still is a bug in Chrome.

To reproduce:
- collapse a comment
- expand the comment
- click on the edit button (after exiting of directly)

What is expected: enter edit mode
What happens: nothing

Investigate whether the event handlers are unlinked when minimizing ?
